services:
  local:
    container_name: awstools_local
    image: awstools_local
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BASE: /home/tool
    working_dir: /home/tool
    volumes:
      - .:/home/tool
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}

  lambda:
    container_name: awstools_lambda
    image: awstools_lambda
    build:
      context: .
      dockerfile: ./lambda/Dockerfile
    ports:
      - 9000:8080
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}