[tool.poetry]
name = "awstools"
version = "0.1.0"
description = ""
authors = ["user.name <gmail@hdknr.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
boto3 = "^1.34.154"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
